SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE*30*(100-P.DISCOUNT_RATE)/100) 'FEE'
FROM CAR_RENTAL_COMPANY_CAR C JOIN (SELECT CAR_TYPE, DISCOUNT_RATE
         FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
         WHERE DURATION_TYPE = '30일 이상') P ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_ID NOT IN (SELECT CAR_ID
                      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                      WHERE END_DATE > '2022-11-00'
                      AND START_DATE < '2022-12-00')
AND C.CAR_TYPE IN ('SUV', '세단')
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;
#     CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON (C.CAR_TYPE = P.CAR_TYPE
# WHERE C.CAR_TYPE IN ('세단', 'SUV') AND ;

















# SELECT DISTINCT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE*30*(100-P.DISCOUNT_RATE)/100) 'FEE'
# FROM CAR_RENTAL_COMPANY_CAR C JOIN (SELECT CAR_TYPE, DISCOUNT_RATE
#                                    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
#                                    WHERE DURATION_TYPE = '30일 이상') P
# ON C.CAR_TYPE = P.CAR_TYPE
# WHERE C.CAR_ID NOT IN (SELECT CAR_ID
#                       FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#                       WHERE END_DATE > '2022-11-00'
#                       AND START_DATE < '2022-12-00')
# AND C.CAR_TYPE IN ('SUV', '세단')
# HAVING FEE >= 500000 AND FEE < 2000000
# ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;