-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, CONCAT(U.CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) '전체주소', CONCAT(SUBSTR(TLNO,1,3), "-", SUBSTR(TLNO,4,4), "-", SUBSTR(TLNO,8,4)) as '전화번호'
FROM USED_GOODS_BOARD B JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
WHERE WRITER_ID = USER_ID
GROUP BY USER_ID
HAVING COUNT(WRITER_ID) >= 3
ORDER BY USER_ID DESC;

# SELECT SUBSTR(TLNO, 1, 3), SUBSTRING(TLNO, 4, 4), SUBSTRING(TLNO, 8, 4),TLNO
# FROM USED_GOODS_USER;

