SELECT USER_ID, NICKNAME, CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) '전체주소', CASE WHEN LENGTH(TLNO) = 10 THEN CONCAT(SUBSTRING(TLNO, 1, 3), '-', SUBSTRING(TLNO, 4, 3), '-', SUBSTRING(TLNO, 7, 4))
                                    ELSE CONCAT(SUBSTRING(TLNO, 1, 3), '-', SUBSTRING(TLNO, 4, 4), '-', SUBSTRING(TLNO, 8, 4)) END '전화번호'
FROM USED_GOODS_USER U JOIN USED_GOODS_BOARD B ON U.USER_ID = B.WRITER_ID
GROUP BY WRITER_ID
HAVING COUNT(BOARD_ID) >= 3
ORDER BY USER_ID DESC;