-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, COUNT(DISTINCT S.USER_ID) PURCHASED_USER,
ROUND((COUNT(DISTINCT S.USER_ID)/(SELECT COUNT(DISTINCT USER_ID) FROM USER_INFO WHERE YEAR(JOINED)=2021)),1)
FROM ONLINE_SALE S JOIN USER_INFO I ON S.USER_ID = I.USER_ID
WHERE YEAR(JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;




















# SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, COUNT(DISTINCT U.USER_ID) PURCHASED_USERS, ROUND(COUNT(DISTINCT U.USER_ID)/(SELECT COUNT(USER_ID)
#                        FROM USER_INFO
#                        WHERE YEAR(JOINED) = 2021), 1) 'PURCHASED_RATIO'
# FROM USER_INFO U JOIN ONLINE_SALE O ON U.USER_ID = O.USER_ID
# WHERE YEAR(JOINED) = 2021
# GROUP BY YEAR, MONTH
# ORDER BY YEAR ASC, MONTH ASC