-- 코드를 입력하세요
# SELECT H.CAR_ID, CASE WHEN T.CAR_ID IS NULL THEN '대여중'
#                     WHEN T.CAR_ID IS NOT NULL THEN '대여 가능' END 'AVAILABILITY'
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H LEFT JOIN (SELECT HISTORY_ID, CAR_ID
#                                               FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#                                               WHERE END_DATE < '2022-10-16' OR START_DATE > '2022-10-16') T ON H.HISTORY_ID = T.HISTORY_ID
# ORDER BY H.CAR_ID DESC;

SELECT H.CAR_ID, CASE WHEN T.CAR_ID IS NULL THEN '대여 가능' ELSE '대여중' END 'AVAILABILITY'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H 
LEFT JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16'
    GROUP BY CAR_ID
    ) T ON H.CAR_ID = T.CAR_ID
GROUP BY H.CAR_ID
ORDER BY H.CAR_ID DESC;