-- 코드를 입력하세요
SELECT B.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES*PRICE) 'TOTAL_SALES'
FROM (BOOK B JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID) JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m-%d') >= DATE_FORMAT('2022-01-01', '%Y-%m-%d') AND DATE_FORMAT(SALES_DATE, '%Y-%m-%d') < DATE_FORMAT('2022-02-01', '%Y-%m-%d')
GROUP BY B.AUTHOR_ID, CATEGORY
ORDER BY B.AUTHOR_ID ASC, CATEGORY DESC;