-- 코드를 입력하세요
# SELECT P.PRODUCT_ID, PRODUCT_NAME, (AMOUNT * PRICE) TOTAL_SALES
# FROM FOOD_PRODUCT P JOIN (SELECT PRODUCT_ID, SUM(AMOUNT) AMOUNT
#                          FROM FOOD_ORDER
#                          WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = DATE_FORMAT('2022-05-01', '%Y-%m')
#                          GROUP BY PRODUCT_ID) T ON P.PRODUCT_ID = T.PRODUCT_ID
# ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC;



SELECT P.PRODUCT_ID, PRODUCT_NAME, (SUM(AMOUNT) * PRICE) TOTAL_SALES
FROM FOOD_PRODUCT P JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = DATE_FORMAT('2022-05-01', '%Y-%m')
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC;
















# WITH S AS (
#     SELECT SUM(AMOUNT) AMOUNT, PRODUCT_ID, PRODUCE_DATE
#     FROM FOOD_ORDER
#     WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m-%d') >= DATE_FORMAT('2022-05-01', '%Y-%m-%d') and
# DATE_FORMAT(PRODUCE_DATE, '%Y-%m-%d') < DATE_FORMAT('2022-06-01', '%Y-%m-%d')
#     GROUP BY PRODUCT_ID
# )

# SELECT S.PRODUCT_ID, PRODUCT_NAME, AMOUNT*PRICE TOTAL_SALES
# FROM S JOIN FOOD_PRODUCT P ON S.PRODUCT_ID = P.PRODUCT_ID
# ORDER BY TOTAL_SALES DESC, S.PRODUCT_ID ASC;