-- 코드를 입력하세요
WITH RENT AS (
    SELECT CAR_ID, START_DATE, END_DATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT('2022-10-16', '%Y-%m-%d') >= START_DATE AND DATE_FORMAT('2022-10-16', '%Y-%m-%d') <= END_DATE
    GROUP BY CAR_ID
)

SELECT C.CAR_ID CAR_ID, CASE WHEN R.CAR_ID IS NULL THEN '대여 가능' ELSE '대여중' END AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C LEFT JOIN RENT R ON C.CAR_ID = R.CAR_ID
GROUP BY C.CAR_ID
ORDER BY C.CAR_ID DESC;