-- 코드를 입력하세요
WITH S AS (
    SELECT SUM(AMOUNT) AMOUNT, PRODUCT_ID, PRODUCE_DATE
    FROM FOOD_ORDER
    WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m-%d') >= DATE_FORMAT('2022-05-01', '%Y-%m-%d') and
DATE_FORMAT(PRODUCE_DATE, '%Y-%m-%d') < DATE_FORMAT('2022-06-01', '%Y-%m-%d')
    GROUP BY PRODUCT_ID
)

SELECT S.PRODUCT_ID, PRODUCT_NAME, AMOUNT*PRICE TOTAL_SALES
FROM S LEFT JOIN FOOD_PRODUCT P ON S.PRODUCT_ID = P.PRODUCT_ID
WHERE PRODUCT_NAME IS NOT NULL
ORDER BY TOTAL_SALES DESC, S.PRODUCT_ID ASC;