-- 코드를 작성해주세요
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT DISTINCT CASE WHEN PARENT_ITEM_ID IS NOT NULL THEN T.ITEM_ID
    WHEN PARENT_ITEM_ID IS NULL THEN I.ITEM_ID END AS ITEM_ID
    FROM ITEM_INFO I JOIN ITEM_TREE T ON T.PARENT_ITEM_ID = I.ITEM_ID
    WHERE RARITY = 'RARE'
)
ORDER BY ITEM_ID DESC