-- 코드를 입력하세요
SELECT MCDP_CD '진료과 코드', COUNT(PT_NO) '5월예약건수'
FROM APPOINTMENT
WHERE DATE_FORMAT(APNT_YMD, '%Y-%m') = DATE_FORMAT('2022-05-01', '%Y-%m')
GROUP BY MCDP_CD
ORDER BY COUNT(PT_NO) ASC, MCDP_CD ASC;