SELECT CATEGORY, SUM(SALES) TOTAL_SALES
FROM BOOK_SALES S JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = DATE_FORMAT('2022-01-01', '%Y-%m')
GROUP BY CATEGORY
ORDER BY CATEGORY ASC;