-- 코드를 작성해주세요
# SELECT BIN(CODE)
# FROM SKILLCODES

WITH A AS (
    SELECT *
    FROM DEVELOPERS NATURAL JOIN SKILLCODES
    WHERE CODE & SKILL_CODE = CODE
)

select GRADE, ID, EMAIL
FROM (
    SELECT DISTINCT ID, EMAIL,
    CASE WHEN ID IN (
        (SELECT ID FROM A WHERE CATEGORY = 'Front End')
        INTERSECT
        (SELECT ID FROM A WHERE NAME = 'Python')
    ) THEN 'A'
    WHEN ID IN (SELECT ID FROM A WHERE NAME = 'C#') THEN 'B'
    WHEN ID IN (SELECT ID FROM A WHERE CATEGORY = 'Front End') THEN 'C'
    END GRADE
    FROM A
) B
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID

# SELECT ID, EMAIL, BIN(SKILL_CODE)
# FROM DEVELOPERS

# 100 B
# 10000 F
# 10000000 B
# 100000000 B PYTHON
# 10000000000 B C#
# 100000000000 F
# 10000000000000 F
# 100000000000000 B

# A클래스 먼저 구하고

# B클래스 구하고

# C클래스 구하자