-- 코드를 입력하세요
# SELECT I.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, REVIEW_SCORE
# FROM REST_INFO I JOIN REST_REVIEW R ON I.REST_ID = R.REST_ID
# WHERE ADDRESS LIKE '서울특별시%';
# ORDER BY SCORE DESC, FAVORITES ASC;

# , ROUND(AVG(REVIEW_SCORE), 2) 'SCORE'

SELECT I.REST_ID 'REST_ID', REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) 'SCORE'
FROM REST_INFO I JOIN REST_REVIEW R ON I.REST_ID = R.REST_ID
GROUP BY I.REST_ID
HAVING ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC;